version: "2"
services:
    mongodb:
        image: mongo:latest
        ports:
          - "27017:27017"
    mongo-seed:
        build:
          context: .
          dockerfile: mongo.Dockerfile
        links:
          - mongodb